from env import EmailTriageEnv
from models import EmailAction
env = EmailTriageEnv()
obs = env.reset()
print("RESET")
print("Email: " + obs.subject)
print("Sender: " + obs.sender)
print("STEP 1 Easy Task")
obs, reward = env.step(EmailAction(action="delete"))
print("Score: " + str(reward.reward))
print("Info: " + reward.info)
print("STEP 2 Medium Task")
obs, reward = env.step(EmailAction(action="reply"))
print("Score: " + str(reward.reward))
print("Info: " + reward.info)
print("STEP 3 Hard Task")
obs, reward = env.step(EmailAction(action="escalate"))
print("Score: " + str(reward.reward))
print("Info: " + reward.info)
print("STATE")
print(env.state())